import React, { createContext, useContext, useMemo, useState } from "react";

const LanguageContext = createContext(null);

const dictionary = {
  en: {
    navRentals:"Vacation Rentals",
    navSales:"Properties For Sale",
    navOwner:"Owner Services",
    navAdmin:"Admin",
    contact:"Contact",
    search:"Search",
    viewRentals:"View Rentals",
    propertiesForSale:"Properties For Sale",
    destinationOrProperty:"Destination or Property ID",
    checkIn:"Check-in",
    checkOut:"Check-out",
    guests:"Guests",
    luxuryBeachfront:"Luxury Beachfront Living",
    homeHeroTitle:"Rent or Own Your Dream Home in Playa Escondida",
    homeHeroText:"Luxury vacation rentals and properties for sale in a tropical paradise. Search by date range and guests to find the right stay faster.",
    homeNote:"Direct sales from the promoter · Best attention and best price",
    vipListings:"VIP Listings",
    featuredRentals:"Featured high-end vacation rentals",
    otherListings:"Other Listings",
    moreRentalOptions:"More vacation rental options",
    rentalsHeading:"Browse available vacation rentals",
    rentalsSub:"Filter by date range, guest count, and keywords.",
    reserveProperty:"Reserve this property",
    continueBooking:"Continue to Booking",
    ownerAccess:"Owner Access",
    ownerId:"Login ID",
    ownerPassword:"Password",
    propertyCalendar:"Property Availability Calendar",
    selectedRange:"Selected range",
    selectedStart:"Selected start date",
    nightsSelected:"Nights selected",
    clickRange:"Click one available date for check-in and a second available date for check-out.",
    bookingCalculator:"Booking Cost Calculator",
    chooseDatesItems:"Choose dates and optional items",
    cleaningFee:"Cleaning fee",
    insurance:"Insurance",
    nightlyRate:"Nightly rate",
    nights:"Nights",
    accommodation:"Accommodation",
    total:"Total",
    bedrooms:"Bedrooms",
    bathrooms:"Bathrooms",
    sqMeters:"Sq Meters",
    sqFeet:"Sq Feet",
    nightly:"Nightly Rate",
    availableResults:"Results",
    signIn:"Sign In",
    signUp:"Sign Up",
    email:"Email",
    password:"Password",
    displayName:"Display Name",
    role:"Role",
    guest:"Guest",
    owner:"Owner",
    admin:"Admin",
    createAccount:"Create Account",
    ownerDashboard:"Owner Dashboard",
    adminDashboard:"Admin Dashboard",
  },
  es: {
    navRentals:"Alquileres Vacacionales",
    navSales:"Propiedades en Venta",
    navOwner:"Servicios al Propietario",
    navAdmin:"Admin",
    contact:"Contacto",
    search:"Buscar",
    viewRentals:"Ver Alquileres",
    propertiesForSale:"Propiedades en Venta",
    destinationOrProperty:"Destino o ID de Propiedad",
    checkIn:"Entrada",
    checkOut:"Salida",
    guests:"Huéspedes",
    luxuryBeachfront:"Vida de Lujo Frente al Mar",
    homeHeroTitle:"Renta o Compra la Casa de tus Sueños en Playa Escondida",
    homeHeroText:"Alquileres vacacionales de lujo y propiedades en venta en un paraíso tropical. Busca por rango de fechas y huéspedes para encontrar la estadía ideal más rápido.",
    homeNote:"Ventas directas de la promotora · Mejor atención y mejor precio",
    vipListings:"Listado VIP",
    featuredRentals:"Alquileres vacacionales destacados",
    otherListings:"Otros Listados",
    moreRentalOptions:"Más opciones de alquiler vacacional",
    rentalsHeading:"Explora alquileres vacacionales disponibles",
    rentalsSub:"Filtra por rango de fechas, cantidad de huéspedes y palabras clave.",
    reserveProperty:"Reserva esta propiedad",
    continueBooking:"Continuar a Reserva",
    ownerAccess:"Acceso del Propietario",
    ownerId:"ID de ingreso",
    ownerPassword:"Contraseña",
    propertyCalendar:"Calendario de Disponibilidad",
    selectedRange:"Rango seleccionado",
    selectedStart:"Fecha inicial seleccionada",
    nightsSelected:"Noches seleccionadas",
    clickRange:"Haz clic en una fecha disponible para entrada y en una segunda fecha disponible para salida.",
    bookingCalculator:"Calculadora de Reserva",
    chooseDatesItems:"Elige fechas y cargos opcionales",
    cleaningFee:"Limpieza",
    insurance:"Seguro",
    nightlyRate:"Tarifa por noche",
    nights:"Noches",
    accommodation:"Hospedaje",
    total:"Total",
    bedrooms:"Habitaciones",
    bathrooms:"Baños",
    sqMeters:"M²",
    sqFeet:"Pies²",
    nightly:"Tarifa por noche",
    availableResults:"Resultados",
    signIn:"Ingresar",
    signUp:"Crear cuenta",
    email:"Correo",
    password:"Contraseña",
    displayName:"Nombre",
    role:"Rol",
    guest:"Huésped",
    owner:"Propietario",
    admin:"Admin",
    createAccount:"Crear Cuenta",
    ownerDashboard:"Panel del Propietario",
    adminDashboard:"Panel Admin",
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState("en");
  const value = useMemo(() => ({ language, setLanguage, t: dictionary[language] }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
